### ISSUE TITLE
Cannot read property 'messages' of undefined

### ISSUE THREAD

**Issue by Andrew-Dyachenko** [michael-ciniawsky/posthtml-w3c#6]
Got this error at the project build
I'm using `posthtml-w3c: 0.9.0` and `parcel: 2.0.0-beta.2`

```bash
@parcel/workers: Cannot read property 'messages' of undefined
TypeError: Cannot read property 'messages' of undefined
    at callback (/Users/andrey/Sites/main-site/src/client/node_modules/posthtml-w3c/index.js:31:15)
    at /Users/andrey/Sites/main-site/src/client/node_modules/w3cjs/lib/w3cjs.js:54:4
    at Request.callback (/Users/andrey/Sites/main-site/src/client/node_modules/superagent/lib/node/index.js:728:3)
    at IncomingMessage.<anonymous> (/Users/andrey/Sites/main-site/src/client/node_modules/superagent/lib/node/index.js:916:18)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**.posthtmlrc**
```json
{
    "plugins":{
        "posthtml-hash": {},
        "posthtml-w3c": {
            "filter": [
                "This document appears to be written in Lorem ipsum text but the “html” start tag has “lang=\"en\"”. Consider using “lang=\"zxx\"” (or variant) instead."
            ],
            "hideEmpty": true
        }
    }
}
```

Might the problem be at the line?
```js
res.messages.shift()
```

*src/client/node_modules/posthtml-w3c/index.js*
```js
w3c.validate({
    input: render(tree),
    output: 'json',
    callback: function (err, res) {
        res.messages.shift()
        res.messages.shift()

        const filtered = res.messages
            .filter(msg => !options.filter.some(s => msg.message.includes(s)))

        let table = tab(filtered.map(msg => {
            let row = [
                `\n${type(msg.type) + ' ' + line(msg.lastLine, msg.firstColumn)}`,
                `\n${message(msg.message)}`
            ]

            return row
        }), { align: 'l', hsep: '' })

        let result = filtered.length

        if (result > 0 || !options.hideEmpty) {
            title('\nPostHTML W3C Validation')
        }

        if (result > 0) {
            console.log(table)
        }

        if (result === 0 && !options.hideEmpty) {
            console.log(chalk.green(`\n${log.success}  ${result} Errors`))
        } else if (result > 0) {
            console.log(chalk.red(`\n${log.warning}  ${result} Errors`))
        }

        resolve(tree);
    }
})
```

**Comment by Scrum** [comment]
@Andrew-Dyachenko Hi, thanks for the feedback. Try updating your package version to 0.9.1

**Comment by Andrew-Dyachenko** [comment]
Update from `0.9.0` to `0.9.1` helped!
Thank you for the patch!
